// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Onboarding.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Address;
@class EmergencyContact;
@class GPBTimestamp;
@class Phone;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MaritalStatus

typedef GPB_ENUM(MaritalStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MaritalStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MaritalStatus_Married = 0,
  MaritalStatus_Divorced = 1,
  MaritalStatus_Widowed = 2,
  MaritalStatus_NeverMarried = 3,
  MaritalStatus_Separated = 4,
};

GPBEnumDescriptor *MaritalStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MaritalStatus_IsValidValue(int32_t value);

#pragma mark - Enum CompanyEvent_CompanyStatus

typedef GPB_ENUM(CompanyEvent_CompanyStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CompanyEvent_CompanyStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CompanyEvent_CompanyStatus_Active = 0,
  CompanyEvent_CompanyStatus_Test = 1,
  CompanyEvent_CompanyStatus_Disabled = 2,
  CompanyEvent_CompanyStatus_Template = 3,
};

GPBEnumDescriptor *CompanyEvent_CompanyStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CompanyEvent_CompanyStatus_IsValidValue(int32_t value);

#pragma mark - Enum CompanyStaffEvent_CompanyStaffStatus

typedef GPB_ENUM(CompanyStaffEvent_CompanyStaffStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CompanyStaffEvent_CompanyStaffStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CompanyStaffEvent_CompanyStaffStatus_Active = 0,
  CompanyStaffEvent_CompanyStaffStatus_Disabled = 1,
};

GPBEnumDescriptor *CompanyStaffEvent_CompanyStaffStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CompanyStaffEvent_CompanyStaffStatus_IsValidValue(int32_t value);

#pragma mark - OnboardingRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OnboardingRoot : GPBRootObject
@end

#pragma mark - CompanyEvent

typedef GPB_ENUM(CompanyEvent_FieldNumber) {
  CompanyEvent_FieldNumber_Uuid = 1,
  CompanyEvent_FieldNumber_Id_p = 2,
  CompanyEvent_FieldNumber_CreatedAt = 3,
  CompanyEvent_FieldNumber_UpdatedAt = 4,
  CompanyEvent_FieldNumber_Name = 5,
  CompanyEvent_FieldNumber_Status = 6,
};

GPB_FINAL @interface CompanyEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *createdAt;
/** Test to see if @c createdAt has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedAt;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedAt;
/** Test to see if @c updatedAt has been set. */
@property(nonatomic, readwrite) BOOL hasUpdatedAt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) CompanyEvent_CompanyStatus status;

@end

/**
 * Fetches the raw value of a @c CompanyEvent's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CompanyEvent_Status_RawValue(CompanyEvent *message);
/**
 * Sets the raw value of an @c CompanyEvent's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCompanyEvent_Status_RawValue(CompanyEvent *message, int32_t value);

#pragma mark - EmployeeEvent

typedef GPB_ENUM(EmployeeEvent_FieldNumber) {
  EmployeeEvent_FieldNumber_Uuid = 1,
  EmployeeEvent_FieldNumber_Id_p = 2,
  EmployeeEvent_FieldNumber_CreatedAt = 3,
  EmployeeEvent_FieldNumber_UpdatedAt = 4,
  EmployeeEvent_FieldNumber_CompanyId = 5,
};

GPB_FINAL @interface EmployeeEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *createdAt;
/** Test to see if @c createdAt has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedAt;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedAt;
/** Test to see if @c updatedAt has been set. */
@property(nonatomic, readwrite) BOOL hasUpdatedAt;

@property(nonatomic, readwrite) int64_t companyId;

@end

#pragma mark - CompanyStaffEvent

typedef GPB_ENUM(CompanyStaffEvent_FieldNumber) {
  CompanyStaffEvent_FieldNumber_Uuid = 1,
  CompanyStaffEvent_FieldNumber_Id_p = 2,
  CompanyStaffEvent_FieldNumber_CreatedAt = 3,
  CompanyStaffEvent_FieldNumber_UpdatedAt = 4,
  CompanyStaffEvent_FieldNumber_Status = 5,
  CompanyStaffEvent_FieldNumber_CompanyId = 6,
  CompanyStaffEvent_FieldNumber_Name = 7,
  CompanyStaffEvent_FieldNumber_Email = 8,
  CompanyStaffEvent_FieldNumber_Phone = 9,
};

GPB_FINAL @interface CompanyStaffEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *createdAt;
/** Test to see if @c createdAt has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedAt;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedAt;
/** Test to see if @c updatedAt has been set. */
@property(nonatomic, readwrite) BOOL hasUpdatedAt;

@property(nonatomic, readwrite) CompanyStaffEvent_CompanyStaffStatus status;

@property(nonatomic, readwrite) int64_t companyId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, strong, null_resettable) Phone *phone;
/** Test to see if @c phone has been set. */
@property(nonatomic, readwrite) BOOL hasPhone;

@end

/**
 * Fetches the raw value of a @c CompanyStaffEvent's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CompanyStaffEvent_Status_RawValue(CompanyStaffEvent *message);
/**
 * Sets the raw value of an @c CompanyStaffEvent's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCompanyStaffEvent_Status_RawValue(CompanyStaffEvent *message, int32_t value);

#pragma mark - EmergencyContact

typedef GPB_ENUM(EmergencyContact_FieldNumber) {
  EmergencyContact_FieldNumber_Relationship = 1,
  EmergencyContact_FieldNumber_FirstName = 2,
  EmergencyContact_FieldNumber_LastName = 3,
  EmergencyContact_FieldNumber_HomePhone = 4,
  EmergencyContact_FieldNumber_WorkPhone = 5,
  EmergencyContact_FieldNumber_Email = 6,
  EmergencyContact_FieldNumber_Address = 7,
};

GPB_FINAL @interface EmergencyContact : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *relationship;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *homePhone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *workPhone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, strong, null_resettable) Address *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - EmployeeInformationEvent

typedef GPB_ENUM(EmployeeInformationEvent_FieldNumber) {
  EmployeeInformationEvent_FieldNumber_Uuid = 1,
  EmployeeInformationEvent_FieldNumber_Id_p = 2,
  EmployeeInformationEvent_FieldNumber_CreatedAt = 3,
  EmployeeInformationEvent_FieldNumber_UpdatedAt = 4,
  EmployeeInformationEvent_FieldNumber_CompanyId = 5,
  EmployeeInformationEvent_FieldNumber_EmployeeId = 6,
  EmployeeInformationEvent_FieldNumber_FirstName = 7,
  EmployeeInformationEvent_FieldNumber_MiddleName = 8,
  EmployeeInformationEvent_FieldNumber_LastName = 9,
  EmployeeInformationEvent_FieldNumber_PriorLastName = 10,
  EmployeeInformationEvent_FieldNumber_PreferedName = 11,
  EmployeeInformationEvent_FieldNumber_Salutation = 12,
  EmployeeInformationEvent_FieldNumber_Ethnicity = 13,
  EmployeeInformationEvent_FieldNumber_Gender = 14,
  EmployeeInformationEvent_FieldNumber_MaritalStatus = 15,
  EmployeeInformationEvent_FieldNumber_Ssn = 16,
  EmployeeInformationEvent_FieldNumber_Smoker = 17,
  EmployeeInformationEvent_FieldNumber_Nationality = 18,
  EmployeeInformationEvent_FieldNumber_DateOfBirth = 19,
  EmployeeInformationEvent_FieldNumber_HomeEmail = 31,
  EmployeeInformationEvent_FieldNumber_HomePhone = 32,
  EmployeeInformationEvent_FieldNumber_HomeAddress = 33,
  EmployeeInformationEvent_FieldNumber_WorkLocationName = 41,
  EmployeeInformationEvent_FieldNumber_WorkEmail = 42,
  EmployeeInformationEvent_FieldNumber_WorkPhone = 43,
  EmployeeInformationEvent_FieldNumber_WorkAddress = 44,
  EmployeeInformationEvent_FieldNumber_EmergencyContactArray = 51,
  EmployeeInformationEvent_FieldNumber_ApplyDate = 52,
  EmployeeInformationEvent_FieldNumber_HireDate = 53,
  EmployeeInformationEvent_FieldNumber_StartDate = 54,
  EmployeeInformationEvent_FieldNumber_TerminationDate = 55,
  EmployeeInformationEvent_FieldNumber_JobTitle = 56,
  EmployeeInformationEvent_FieldNumber_DepartmentName = 57,
};

GPB_FINAL @interface EmployeeInformationEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *createdAt;
/** Test to see if @c createdAt has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedAt;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedAt;
/** Test to see if @c updatedAt has been set. */
@property(nonatomic, readwrite) BOOL hasUpdatedAt;

@property(nonatomic, readwrite) int64_t companyId;

@property(nonatomic, readwrite) int64_t employeeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *middleName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *priorLastName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *preferedName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salutation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ethnicity;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

@property(nonatomic, readwrite) MaritalStatus maritalStatus;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ssn;

@property(nonatomic, readwrite) BOOL smoker;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nationality;

@property(nonatomic, readwrite, copy, null_resettable) NSString *dateOfBirth;

/** Home Address */
@property(nonatomic, readwrite, copy, null_resettable) NSString *homeEmail;

@property(nonatomic, readwrite, strong, null_resettable) Phone *homePhone;
/** Test to see if @c homePhone has been set. */
@property(nonatomic, readwrite) BOOL hasHomePhone;

@property(nonatomic, readwrite, strong, null_resettable) Address *homeAddress;
/** Test to see if @c homeAddress has been set. */
@property(nonatomic, readwrite) BOOL hasHomeAddress;

/** Work Address */
@property(nonatomic, readwrite, copy, null_resettable) NSString *workLocationName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *workEmail;

@property(nonatomic, readwrite, strong, null_resettable) Phone *workPhone;
/** Test to see if @c workPhone has been set. */
@property(nonatomic, readwrite) BOOL hasWorkPhone;

@property(nonatomic, readwrite, strong, null_resettable) Address *workAddress;
/** Test to see if @c workAddress has been set. */
@property(nonatomic, readwrite) BOOL hasWorkAddress;

/** Emergency Contact */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EmergencyContact*> *emergencyContactArray;
/** The number of items in @c emergencyContactArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger emergencyContactArray_Count;

/** Employment details */
@property(nonatomic, readwrite, copy, null_resettable) NSString *applyDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hireDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *startDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *terminationDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jobTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *departmentName;

@end

/**
 * Fetches the raw value of a @c EmployeeInformationEvent's @c maritalStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t EmployeeInformationEvent_MaritalStatus_RawValue(EmployeeInformationEvent *message);
/**
 * Sets the raw value of an @c EmployeeInformationEvent's @c maritalStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetEmployeeInformationEvent_MaritalStatus_RawValue(EmployeeInformationEvent *message, int32_t value);

#pragma mark - EmployeeInitialStateEvent

typedef GPB_ENUM(EmployeeInitialStateEvent_FieldNumber) {
  EmployeeInitialStateEvent_FieldNumber_Uuid = 1,
  EmployeeInitialStateEvent_FieldNumber_Id_p = 2,
  EmployeeInitialStateEvent_FieldNumber_CreatedAt = 3,
  EmployeeInitialStateEvent_FieldNumber_UpdatedAt = 4,
  EmployeeInitialStateEvent_FieldNumber_EmployeeId = 5,
  EmployeeInitialStateEvent_FieldNumber_FirstName = 6,
  EmployeeInitialStateEvent_FieldNumber_LastName = 7,
};

GPB_FINAL @interface EmployeeInitialStateEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *createdAt;
/** Test to see if @c createdAt has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedAt;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedAt;
/** Test to see if @c updatedAt has been set. */
@property(nonatomic, readwrite) BOOL hasUpdatedAt;

@property(nonatomic, readwrite) int64_t employeeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

/**  google.protobuf.Timestamp applied_date =9; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
