# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common/Phone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common/Phone.proto',
  package='Workstream.Protocol.Common',
  syntax='proto3',
  serialized_options=b'Z workstream_protocol/common/phone',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x43ommon/Phone.proto\x12\x1aWorkstream.Protocol.Common\"@\n\x05Phone\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x11\n\textension\x18\x03 \x01(\tB\"Z workstream_protocol/common/phoneb\x06proto3'
)




_PHONE = _descriptor.Descriptor(
  name='Phone',
  full_name='Workstream.Protocol.Common.Phone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_code', full_name='Workstream.Protocol.Common.Phone.country_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='Workstream.Protocol.Common.Phone.number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extension', full_name='Workstream.Protocol.Common.Phone.extension', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['Phone'] = _PHONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Phone = _reflection.GeneratedProtocolMessageType('Phone', (_message.Message,), {
  'DESCRIPTOR' : _PHONE,
  '__module__' : 'Common.Phone_pb2'
  # @@protoc_insertion_point(class_scope:Workstream.Protocol.Common.Phone)
  })
_sym_db.RegisterMessage(Phone)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
