// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common/Address.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(CountryCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AddressRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AddressRoot : GPBRootObject
@end

#pragma mark - Address

typedef GPB_ENUM(Address_FieldNumber) {
  Address_FieldNumber_Address1 = 1,
  Address_FieldNumber_Address2 = 2,
  Address_FieldNumber_City = 3,
  Address_FieldNumber_County = 4,
  Address_FieldNumber_CountrySubDivisionCode = 19,
  Address_FieldNumber_Zip = 20,
  Address_FieldNumber_CountryCode = 21,
};

GPB_FINAL @interface Address : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *city;

@property(nonatomic, readwrite, copy, null_resettable) NSString *county;

@property(nonatomic, readwrite, copy, null_resettable) NSString *zip;

@property(nonatomic, readwrite, copy, null_resettable) NSString *countrySubDivisionCode;

@property(nonatomic, readwrite) enum CountryCode countryCode;

@end

/**
 * Fetches the raw value of a @c Address's @c countryCode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Address_CountryCode_RawValue(Address *message);
/**
 * Sets the raw value of an @c Address's @c countryCode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddress_CountryCode_RawValue(Address *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
