// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common/CountryCode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Common/CountryCode.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CountryCodeRoot

@implementation CountryCodeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum CountryCode

GPBEnumDescriptor *CountryCode_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Af\000Ax\000Al\000Dz\000As\000Ad\000Ao\000Ai\000Aq\000Ag\000Ar\000Am\000Aw\000A"
        "u\000At\000Az\000Bs\000Bh\000Bd\000Bb\000By\000Be\000Bz\000Bj\000Bm\000Bt\000Bo"
        "\000Bq\000Ba\000Bw\000Bv\000Br\000Io\000Bn\000Bg\000Bf\000Bi\000Kh\000Cm\000Ca\000"
        "Cv\000Ky\000Cf\000Td\000Cl\000Cn\000Cx\000Cc\000Co\000Km\000Cg\000Cd\000Ck\000C"
        "r\000Ci\000Hr\000Cu\000Cw\000Cy\000Cz\000Dk\000Dj\000Dm\000Do\000Ec\000Eg\000Sv"
        "\000Gq\000Er\000Ee\000Et\000Fk\000Fo\000Fj\000Fi\000Fr\000Gf\000Pf\000Tf\000Ga\000"
        "Gm\000Ge\000De\000Gh\000Gi\000Gr\000Gl\000Gd\000Gp\000Gu\000Gt\000Gg\000Gn\000G"
        "w\000Gy\000Ht\000Hm\000Va\000Hn\000Hk\000Hu\000Is\000In\000Id\000Ir\000Iq\000Ie"
        "\000Im\000Il\000It\000Jm\000Jp\000Je\000Jo\000Kz\000Ke\000Ki\000Kp\000Kr\000Kw\000"
        "Kg\000La\000Lv\000Lb\000Ls\000Lr\000Ly\000Li\000Lt\000Lu\000Mo\000Mk\000Mg\000M"
        "w\000My\000Mv\000Ml\000Mt\000Mh\000Mq\000Mr\000Mu\000Yt\000Mx\000Fm\000Md\000Mc"
        "\000Mn\000Me\000Ms\000Ma\000Mz\000Mm\000Na\000Nr\000Np\000Nl\000Nc\000Nz\000Ni\000"
        "Ne\000Ng\000Nu\000Nf\000Mp\000No\000Om\000Pk\000Pw\000Ps\000Pa\000Pg\000Py\000P"
        "e\000Ph\000Pn\000Pl\000Pt\000Pr\000Qa\000Re\000Ro\000Ru\000Rw\000Bl\000Sh\000Kn"
        "\000Lc\000Mf\000Pm\000Vc\000Ws\000Sm\000St\000Sa\000Sn\000Rs\000Sc\000Sl\000Sg\000"
        "Sx\000Sk\000Si\000Sb\000So\000Za\000Gs\000Ss\000Es\000Lk\000Sd\000Sr\000Sj\000S"
        "z\000Se\000Ch\000Sy\000Tw\000Tj\000Tz\000Th\000Tl\000Tg\000Tk\000To\000Tt\000Tn"
        "\000Tr\000Tm\000Tc\000Tv\000Ug\000Ua\000Ae\000Gb\000Us\000Um\000Uy\000Uz\000Vu\000"
        "Ve\000Vn\000Vg\000Vi\000Wf\000Eh\000Ye\000Zm\000Zw\000";
    static const int32_t values[] = {
        CountryCode_Af,
        CountryCode_Ax,
        CountryCode_Al,
        CountryCode_Dz,
        CountryCode_As,
        CountryCode_Ad,
        CountryCode_Ao,
        CountryCode_Ai,
        CountryCode_Aq,
        CountryCode_Ag,
        CountryCode_Ar,
        CountryCode_Am,
        CountryCode_Aw,
        CountryCode_Au,
        CountryCode_At,
        CountryCode_Az,
        CountryCode_Bs,
        CountryCode_Bh,
        CountryCode_Bd,
        CountryCode_Bb,
        CountryCode_By,
        CountryCode_Be,
        CountryCode_Bz,
        CountryCode_Bj,
        CountryCode_Bm,
        CountryCode_Bt,
        CountryCode_Bo,
        CountryCode_Bq,
        CountryCode_Ba,
        CountryCode_Bw,
        CountryCode_Bv,
        CountryCode_Br,
        CountryCode_Io,
        CountryCode_Bn,
        CountryCode_Bg,
        CountryCode_Bf,
        CountryCode_Bi,
        CountryCode_Kh,
        CountryCode_Cm,
        CountryCode_Ca,
        CountryCode_Cv,
        CountryCode_Ky,
        CountryCode_Cf,
        CountryCode_Td,
        CountryCode_Cl,
        CountryCode_Cn,
        CountryCode_Cx,
        CountryCode_Cc,
        CountryCode_Co,
        CountryCode_Km,
        CountryCode_Cg,
        CountryCode_Cd,
        CountryCode_Ck,
        CountryCode_Cr,
        CountryCode_Ci,
        CountryCode_Hr,
        CountryCode_Cu,
        CountryCode_Cw,
        CountryCode_Cy,
        CountryCode_Cz,
        CountryCode_Dk,
        CountryCode_Dj,
        CountryCode_Dm,
        CountryCode_Do,
        CountryCode_Ec,
        CountryCode_Eg,
        CountryCode_Sv,
        CountryCode_Gq,
        CountryCode_Er,
        CountryCode_Ee,
        CountryCode_Et,
        CountryCode_Fk,
        CountryCode_Fo,
        CountryCode_Fj,
        CountryCode_Fi,
        CountryCode_Fr,
        CountryCode_Gf,
        CountryCode_Pf,
        CountryCode_Tf,
        CountryCode_Ga,
        CountryCode_Gm,
        CountryCode_Ge,
        CountryCode_De,
        CountryCode_Gh,
        CountryCode_Gi,
        CountryCode_Gr,
        CountryCode_Gl,
        CountryCode_Gd,
        CountryCode_Gp,
        CountryCode_Gu,
        CountryCode_Gt,
        CountryCode_Gg,
        CountryCode_Gn,
        CountryCode_Gw,
        CountryCode_Gy,
        CountryCode_Ht,
        CountryCode_Hm,
        CountryCode_Va,
        CountryCode_Hn,
        CountryCode_Hk,
        CountryCode_Hu,
        CountryCode_Is,
        CountryCode_In,
        CountryCode_Id,
        CountryCode_Ir,
        CountryCode_Iq,
        CountryCode_Ie,
        CountryCode_Im,
        CountryCode_Il,
        CountryCode_It,
        CountryCode_Jm,
        CountryCode_Jp,
        CountryCode_Je,
        CountryCode_Jo,
        CountryCode_Kz,
        CountryCode_Ke,
        CountryCode_Ki,
        CountryCode_Kp,
        CountryCode_Kr,
        CountryCode_Kw,
        CountryCode_Kg,
        CountryCode_La,
        CountryCode_Lv,
        CountryCode_Lb,
        CountryCode_Ls,
        CountryCode_Lr,
        CountryCode_Ly,
        CountryCode_Li,
        CountryCode_Lt,
        CountryCode_Lu,
        CountryCode_Mo,
        CountryCode_Mk,
        CountryCode_Mg,
        CountryCode_Mw,
        CountryCode_My,
        CountryCode_Mv,
        CountryCode_Ml,
        CountryCode_Mt,
        CountryCode_Mh,
        CountryCode_Mq,
        CountryCode_Mr,
        CountryCode_Mu,
        CountryCode_Yt,
        CountryCode_Mx,
        CountryCode_Fm,
        CountryCode_Md,
        CountryCode_Mc,
        CountryCode_Mn,
        CountryCode_Me,
        CountryCode_Ms,
        CountryCode_Ma,
        CountryCode_Mz,
        CountryCode_Mm,
        CountryCode_Na,
        CountryCode_Nr,
        CountryCode_Np,
        CountryCode_Nl,
        CountryCode_Nc,
        CountryCode_Nz,
        CountryCode_Ni,
        CountryCode_Ne,
        CountryCode_Ng,
        CountryCode_Nu,
        CountryCode_Nf,
        CountryCode_Mp,
        CountryCode_No,
        CountryCode_Om,
        CountryCode_Pk,
        CountryCode_Pw,
        CountryCode_Ps,
        CountryCode_Pa,
        CountryCode_Pg,
        CountryCode_Py,
        CountryCode_Pe,
        CountryCode_Ph,
        CountryCode_Pn,
        CountryCode_Pl,
        CountryCode_Pt,
        CountryCode_Pr,
        CountryCode_Qa,
        CountryCode_Re,
        CountryCode_Ro,
        CountryCode_Ru,
        CountryCode_Rw,
        CountryCode_Bl,
        CountryCode_Sh,
        CountryCode_Kn,
        CountryCode_Lc,
        CountryCode_Mf,
        CountryCode_Pm,
        CountryCode_Vc,
        CountryCode_Ws,
        CountryCode_Sm,
        CountryCode_St,
        CountryCode_Sa,
        CountryCode_Sn,
        CountryCode_Rs,
        CountryCode_Sc,
        CountryCode_Sl,
        CountryCode_Sg,
        CountryCode_Sx,
        CountryCode_Sk,
        CountryCode_Si,
        CountryCode_Sb,
        CountryCode_So,
        CountryCode_Za,
        CountryCode_Gs,
        CountryCode_Ss,
        CountryCode_Es,
        CountryCode_Lk,
        CountryCode_Sd,
        CountryCode_Sr,
        CountryCode_Sj,
        CountryCode_Sz,
        CountryCode_Se,
        CountryCode_Ch,
        CountryCode_Sy,
        CountryCode_Tw,
        CountryCode_Tj,
        CountryCode_Tz,
        CountryCode_Th,
        CountryCode_Tl,
        CountryCode_Tg,
        CountryCode_Tk,
        CountryCode_To,
        CountryCode_Tt,
        CountryCode_Tn,
        CountryCode_Tr,
        CountryCode_Tm,
        CountryCode_Tc,
        CountryCode_Tv,
        CountryCode_Ug,
        CountryCode_Ua,
        CountryCode_Ae,
        CountryCode_Gb,
        CountryCode_Us,
        CountryCode_Um,
        CountryCode_Uy,
        CountryCode_Uz,
        CountryCode_Vu,
        CountryCode_Ve,
        CountryCode_Vn,
        CountryCode_Vg,
        CountryCode_Vi,
        CountryCode_Wf,
        CountryCode_Eh,
        CountryCode_Ye,
        CountryCode_Zm,
        CountryCode_Zw,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CountryCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:CountryCode_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL CountryCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case CountryCode_Af:
    case CountryCode_Ax:
    case CountryCode_Al:
    case CountryCode_Dz:
    case CountryCode_As:
    case CountryCode_Ad:
    case CountryCode_Ao:
    case CountryCode_Ai:
    case CountryCode_Aq:
    case CountryCode_Ag:
    case CountryCode_Ar:
    case CountryCode_Am:
    case CountryCode_Aw:
    case CountryCode_Au:
    case CountryCode_At:
    case CountryCode_Az:
    case CountryCode_Bs:
    case CountryCode_Bh:
    case CountryCode_Bd:
    case CountryCode_Bb:
    case CountryCode_By:
    case CountryCode_Be:
    case CountryCode_Bz:
    case CountryCode_Bj:
    case CountryCode_Bm:
    case CountryCode_Bt:
    case CountryCode_Bo:
    case CountryCode_Bq:
    case CountryCode_Ba:
    case CountryCode_Bw:
    case CountryCode_Bv:
    case CountryCode_Br:
    case CountryCode_Io:
    case CountryCode_Bn:
    case CountryCode_Bg:
    case CountryCode_Bf:
    case CountryCode_Bi:
    case CountryCode_Kh:
    case CountryCode_Cm:
    case CountryCode_Ca:
    case CountryCode_Cv:
    case CountryCode_Ky:
    case CountryCode_Cf:
    case CountryCode_Td:
    case CountryCode_Cl:
    case CountryCode_Cn:
    case CountryCode_Cx:
    case CountryCode_Cc:
    case CountryCode_Co:
    case CountryCode_Km:
    case CountryCode_Cg:
    case CountryCode_Cd:
    case CountryCode_Ck:
    case CountryCode_Cr:
    case CountryCode_Ci:
    case CountryCode_Hr:
    case CountryCode_Cu:
    case CountryCode_Cw:
    case CountryCode_Cy:
    case CountryCode_Cz:
    case CountryCode_Dk:
    case CountryCode_Dj:
    case CountryCode_Dm:
    case CountryCode_Do:
    case CountryCode_Ec:
    case CountryCode_Eg:
    case CountryCode_Sv:
    case CountryCode_Gq:
    case CountryCode_Er:
    case CountryCode_Ee:
    case CountryCode_Et:
    case CountryCode_Fk:
    case CountryCode_Fo:
    case CountryCode_Fj:
    case CountryCode_Fi:
    case CountryCode_Fr:
    case CountryCode_Gf:
    case CountryCode_Pf:
    case CountryCode_Tf:
    case CountryCode_Ga:
    case CountryCode_Gm:
    case CountryCode_Ge:
    case CountryCode_De:
    case CountryCode_Gh:
    case CountryCode_Gi:
    case CountryCode_Gr:
    case CountryCode_Gl:
    case CountryCode_Gd:
    case CountryCode_Gp:
    case CountryCode_Gu:
    case CountryCode_Gt:
    case CountryCode_Gg:
    case CountryCode_Gn:
    case CountryCode_Gw:
    case CountryCode_Gy:
    case CountryCode_Ht:
    case CountryCode_Hm:
    case CountryCode_Va:
    case CountryCode_Hn:
    case CountryCode_Hk:
    case CountryCode_Hu:
    case CountryCode_Is:
    case CountryCode_In:
    case CountryCode_Id:
    case CountryCode_Ir:
    case CountryCode_Iq:
    case CountryCode_Ie:
    case CountryCode_Im:
    case CountryCode_Il:
    case CountryCode_It:
    case CountryCode_Jm:
    case CountryCode_Jp:
    case CountryCode_Je:
    case CountryCode_Jo:
    case CountryCode_Kz:
    case CountryCode_Ke:
    case CountryCode_Ki:
    case CountryCode_Kp:
    case CountryCode_Kr:
    case CountryCode_Kw:
    case CountryCode_Kg:
    case CountryCode_La:
    case CountryCode_Lv:
    case CountryCode_Lb:
    case CountryCode_Ls:
    case CountryCode_Lr:
    case CountryCode_Ly:
    case CountryCode_Li:
    case CountryCode_Lt:
    case CountryCode_Lu:
    case CountryCode_Mo:
    case CountryCode_Mk:
    case CountryCode_Mg:
    case CountryCode_Mw:
    case CountryCode_My:
    case CountryCode_Mv:
    case CountryCode_Ml:
    case CountryCode_Mt:
    case CountryCode_Mh:
    case CountryCode_Mq:
    case CountryCode_Mr:
    case CountryCode_Mu:
    case CountryCode_Yt:
    case CountryCode_Mx:
    case CountryCode_Fm:
    case CountryCode_Md:
    case CountryCode_Mc:
    case CountryCode_Mn:
    case CountryCode_Me:
    case CountryCode_Ms:
    case CountryCode_Ma:
    case CountryCode_Mz:
    case CountryCode_Mm:
    case CountryCode_Na:
    case CountryCode_Nr:
    case CountryCode_Np:
    case CountryCode_Nl:
    case CountryCode_Nc:
    case CountryCode_Nz:
    case CountryCode_Ni:
    case CountryCode_Ne:
    case CountryCode_Ng:
    case CountryCode_Nu:
    case CountryCode_Nf:
    case CountryCode_Mp:
    case CountryCode_No:
    case CountryCode_Om:
    case CountryCode_Pk:
    case CountryCode_Pw:
    case CountryCode_Ps:
    case CountryCode_Pa:
    case CountryCode_Pg:
    case CountryCode_Py:
    case CountryCode_Pe:
    case CountryCode_Ph:
    case CountryCode_Pn:
    case CountryCode_Pl:
    case CountryCode_Pt:
    case CountryCode_Pr:
    case CountryCode_Qa:
    case CountryCode_Re:
    case CountryCode_Ro:
    case CountryCode_Ru:
    case CountryCode_Rw:
    case CountryCode_Bl:
    case CountryCode_Sh:
    case CountryCode_Kn:
    case CountryCode_Lc:
    case CountryCode_Mf:
    case CountryCode_Pm:
    case CountryCode_Vc:
    case CountryCode_Ws:
    case CountryCode_Sm:
    case CountryCode_St:
    case CountryCode_Sa:
    case CountryCode_Sn:
    case CountryCode_Rs:
    case CountryCode_Sc:
    case CountryCode_Sl:
    case CountryCode_Sg:
    case CountryCode_Sx:
    case CountryCode_Sk:
    case CountryCode_Si:
    case CountryCode_Sb:
    case CountryCode_So:
    case CountryCode_Za:
    case CountryCode_Gs:
    case CountryCode_Ss:
    case CountryCode_Es:
    case CountryCode_Lk:
    case CountryCode_Sd:
    case CountryCode_Sr:
    case CountryCode_Sj:
    case CountryCode_Sz:
    case CountryCode_Se:
    case CountryCode_Ch:
    case CountryCode_Sy:
    case CountryCode_Tw:
    case CountryCode_Tj:
    case CountryCode_Tz:
    case CountryCode_Th:
    case CountryCode_Tl:
    case CountryCode_Tg:
    case CountryCode_Tk:
    case CountryCode_To:
    case CountryCode_Tt:
    case CountryCode_Tn:
    case CountryCode_Tr:
    case CountryCode_Tm:
    case CountryCode_Tc:
    case CountryCode_Tv:
    case CountryCode_Ug:
    case CountryCode_Ua:
    case CountryCode_Ae:
    case CountryCode_Gb:
    case CountryCode_Us:
    case CountryCode_Um:
    case CountryCode_Uy:
    case CountryCode_Uz:
    case CountryCode_Vu:
    case CountryCode_Ve:
    case CountryCode_Vn:
    case CountryCode_Vg:
    case CountryCode_Vi:
    case CountryCode_Wf:
    case CountryCode_Eh:
    case CountryCode_Ye:
    case CountryCode_Zm:
    case CountryCode_Zw:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
