// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common/CountryCode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CountryCode

/** ISO 3166-2 */
typedef GPB_ENUM(CountryCode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CountryCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Afghanistan */
  CountryCode_Af = 0,

  /** Ã…land Islands */
  CountryCode_Ax = 1,

  /** Albania */
  CountryCode_Al = 2,

  /** Algeria */
  CountryCode_Dz = 3,

  /** American Samoa */
  CountryCode_As = 4,

  /** Andorra */
  CountryCode_Ad = 5,

  /** Angola */
  CountryCode_Ao = 6,

  /** Anguilla */
  CountryCode_Ai = 7,

  /** Antarctica */
  CountryCode_Aq = 8,

  /** Antigua and Barbuda */
  CountryCode_Ag = 9,

  /** Argentina */
  CountryCode_Ar = 10,

  /** Armenia */
  CountryCode_Am = 11,

  /** Aruba */
  CountryCode_Aw = 12,

  /** Australia */
  CountryCode_Au = 13,

  /** Austria */
  CountryCode_At = 14,

  /** Azerbaijan */
  CountryCode_Az = 15,

  /** Bahamas */
  CountryCode_Bs = 16,

  /** Bahrain */
  CountryCode_Bh = 17,

  /** Bangladesh */
  CountryCode_Bd = 18,

  /** Barbados */
  CountryCode_Bb = 19,

  /** Belarus */
  CountryCode_By = 20,

  /** Belgium */
  CountryCode_Be = 21,

  /** Belize */
  CountryCode_Bz = 22,

  /** Benin */
  CountryCode_Bj = 23,

  /** Bermuda */
  CountryCode_Bm = 24,

  /** Bhutan */
  CountryCode_Bt = 25,

  /** "Bolivia, Plurinational State of" */
  CountryCode_Bo = 26,

  /** "Bonaire, Sint Eustatius and Saba" */
  CountryCode_Bq = 27,

  /** Bosnia and Herzegovina */
  CountryCode_Ba = 28,

  /** Botswana */
  CountryCode_Bw = 29,

  /** Bouvet Island */
  CountryCode_Bv = 30,

  /** Brazil */
  CountryCode_Br = 31,

  /** British Indian Ocean Territory */
  CountryCode_Io = 32,

  /** Brunei Darussalam */
  CountryCode_Bn = 33,

  /** Bulgaria */
  CountryCode_Bg = 34,

  /** Burkina Faso */
  CountryCode_Bf = 35,

  /** Burundi */
  CountryCode_Bi = 36,

  /** Cambodia */
  CountryCode_Kh = 37,

  /** Cameroon */
  CountryCode_Cm = 38,

  /** Canada */
  CountryCode_Ca = 39,

  /** Cape Verde */
  CountryCode_Cv = 40,

  /** Cayman Islands */
  CountryCode_Ky = 41,

  /** Central African Republic */
  CountryCode_Cf = 42,

  /** Chad */
  CountryCode_Td = 43,

  /** Chile */
  CountryCode_Cl = 44,

  /** China */
  CountryCode_Cn = 45,

  /** Christmas Island */
  CountryCode_Cx = 46,

  /** Cocos (Keeling) Islands */
  CountryCode_Cc = 47,

  /** Colombia */
  CountryCode_Co = 48,

  /** Comoros */
  CountryCode_Km = 49,

  /** Congo */
  CountryCode_Cg = 50,

  /** "Congo, the Democratic Republic of the" */
  CountryCode_Cd = 51,

  /** Cook Islands */
  CountryCode_Ck = 52,

  /** Costa Rica */
  CountryCode_Cr = 53,

  /** CÃ´te d'Ivoire */
  CountryCode_Ci = 54,

  /** Croatia */
  CountryCode_Hr = 55,

  /** Cuba */
  CountryCode_Cu = 56,

  /** CuraÃ§ao */
  CountryCode_Cw = 57,

  /** Cyprus */
  CountryCode_Cy = 58,

  /** Czech Republic */
  CountryCode_Cz = 59,

  /** Denmark */
  CountryCode_Dk = 60,

  /** Djibouti */
  CountryCode_Dj = 61,

  /** Dominica */
  CountryCode_Dm = 62,

  /** Dominican Republic */
  CountryCode_Do = 63,

  /** Ecuador */
  CountryCode_Ec = 64,

  /** Egypt */
  CountryCode_Eg = 65,

  /** El Salvador */
  CountryCode_Sv = 66,

  /** Equatorial Guinea */
  CountryCode_Gq = 67,

  /** Eritrea */
  CountryCode_Er = 68,

  /** Estonia */
  CountryCode_Ee = 69,

  /** Ethiopia */
  CountryCode_Et = 70,

  /** Falkland Islands (Malvinas) */
  CountryCode_Fk = 71,

  /** Faroe Islands */
  CountryCode_Fo = 72,

  /** Fiji */
  CountryCode_Fj = 73,

  /** Finland */
  CountryCode_Fi = 74,

  /** France */
  CountryCode_Fr = 75,

  /** French Guiana */
  CountryCode_Gf = 76,

  /** French Polynesia */
  CountryCode_Pf = 77,

  /** French Southern Territories */
  CountryCode_Tf = 78,

  /** Gabon */
  CountryCode_Ga = 79,

  /** Gambia */
  CountryCode_Gm = 80,

  /** Georgia */
  CountryCode_Ge = 81,

  /** Germany */
  CountryCode_De = 82,

  /** Ghana */
  CountryCode_Gh = 83,

  /** Gibraltar */
  CountryCode_Gi = 84,

  /** Greece */
  CountryCode_Gr = 85,

  /** Greenland */
  CountryCode_Gl = 86,

  /** Grenada */
  CountryCode_Gd = 87,

  /** Guadeloupe */
  CountryCode_Gp = 88,

  /** Guam */
  CountryCode_Gu = 89,

  /** Guatemala */
  CountryCode_Gt = 90,

  /** Guernsey */
  CountryCode_Gg = 91,

  /** Guinea */
  CountryCode_Gn = 92,

  /** Guinea-Bissau */
  CountryCode_Gw = 93,

  /** Guyana */
  CountryCode_Gy = 94,

  /** Haiti */
  CountryCode_Ht = 95,

  /** Heard Island and McDonald Islands */
  CountryCode_Hm = 96,

  /** Holy See (Vatican City State) */
  CountryCode_Va = 97,

  /** Honduras */
  CountryCode_Hn = 98,

  /** Hong Kong */
  CountryCode_Hk = 99,

  /** Hungary */
  CountryCode_Hu = 100,

  /** Iceland */
  CountryCode_Is = 101,

  /** India */
  CountryCode_In = 102,

  /** Indonesia */
  CountryCode_Id = 103,

  /** "Iran, Islamic Republic of" */
  CountryCode_Ir = 104,

  /** Iraq */
  CountryCode_Iq = 105,

  /** Ireland */
  CountryCode_Ie = 106,

  /** Isle of Man */
  CountryCode_Im = 107,

  /** Israel */
  CountryCode_Il = 108,

  /** Italy */
  CountryCode_It = 109,

  /** Jamaica */
  CountryCode_Jm = 110,

  /** Japan */
  CountryCode_Jp = 111,

  /** Jersey */
  CountryCode_Je = 112,

  /** Jordan */
  CountryCode_Jo = 113,

  /** Kazakhstan */
  CountryCode_Kz = 114,

  /** Kenya */
  CountryCode_Ke = 115,

  /** Kiribati */
  CountryCode_Ki = 116,

  /** "Korea, Democratic People's Republic of" */
  CountryCode_Kp = 117,

  /** "Korea, Republic of" */
  CountryCode_Kr = 118,

  /** Kuwait */
  CountryCode_Kw = 119,

  /** Kyrgyzstan */
  CountryCode_Kg = 120,

  /** Lao People's Democratic Republic */
  CountryCode_La = 121,

  /** Latvia */
  CountryCode_Lv = 122,

  /** Lebanon */
  CountryCode_Lb = 123,

  /** Lesotho */
  CountryCode_Ls = 124,

  /** Liberia */
  CountryCode_Lr = 125,

  /** Libya */
  CountryCode_Ly = 126,

  /** Liechtenstein */
  CountryCode_Li = 127,

  /** Lithuania */
  CountryCode_Lt = 128,

  /** Luxembourg */
  CountryCode_Lu = 129,

  /** Macao */
  CountryCode_Mo = 130,

  /** "Macedonia, the Former Yugoslav Republic of" */
  CountryCode_Mk = 131,

  /** Madagascar */
  CountryCode_Mg = 132,

  /** Malawi */
  CountryCode_Mw = 133,

  /** Malaysia */
  CountryCode_My = 134,

  /** Maldives */
  CountryCode_Mv = 135,

  /** Mali */
  CountryCode_Ml = 136,

  /** Malta */
  CountryCode_Mt = 137,

  /** Marshall Islands */
  CountryCode_Mh = 138,

  /** Martinique */
  CountryCode_Mq = 139,

  /** Mauritania */
  CountryCode_Mr = 140,

  /** Mauritius */
  CountryCode_Mu = 141,

  /** Mayotte */
  CountryCode_Yt = 142,

  /** Mexico */
  CountryCode_Mx = 143,

  /** "Micronesia, Federated States of" */
  CountryCode_Fm = 144,

  /** "Moldova, Republic of" */
  CountryCode_Md = 145,

  /** Monaco */
  CountryCode_Mc = 146,

  /** Mongolia */
  CountryCode_Mn = 147,

  /** Montenegro */
  CountryCode_Me = 148,

  /** Montserrat */
  CountryCode_Ms = 149,

  /** Morocco */
  CountryCode_Ma = 150,

  /** Mozambique */
  CountryCode_Mz = 151,

  /** Myanmar */
  CountryCode_Mm = 152,

  /** Namibia */
  CountryCode_Na = 153,

  /** Nauru */
  CountryCode_Nr = 154,

  /** Nepal */
  CountryCode_Np = 155,

  /** Netherlands */
  CountryCode_Nl = 156,

  /** New Caledonia */
  CountryCode_Nc = 157,

  /** New Zealand */
  CountryCode_Nz = 158,

  /** Nicaragua */
  CountryCode_Ni = 159,

  /** Niger */
  CountryCode_Ne = 160,

  /** Nigeria */
  CountryCode_Ng = 161,

  /** Niue */
  CountryCode_Nu = 162,

  /** Norfolk Island */
  CountryCode_Nf = 163,

  /** Northern Mariana Islands */
  CountryCode_Mp = 164,

  /** Norway */
  CountryCode_No = 165,

  /** Oman */
  CountryCode_Om = 166,

  /** Pakistan */
  CountryCode_Pk = 167,

  /** Palau */
  CountryCode_Pw = 168,

  /** "Palestine, State of" */
  CountryCode_Ps = 169,

  /** Panama */
  CountryCode_Pa = 170,

  /** Papua New Guinea */
  CountryCode_Pg = 171,

  /** Paraguay */
  CountryCode_Py = 172,

  /** Peru */
  CountryCode_Pe = 173,

  /** Philippines */
  CountryCode_Ph = 174,

  /** Pitcairn */
  CountryCode_Pn = 175,

  /** Poland */
  CountryCode_Pl = 176,

  /** Portugal */
  CountryCode_Pt = 177,

  /** Puerto Rico */
  CountryCode_Pr = 178,

  /** Qatar */
  CountryCode_Qa = 179,

  /** RÃ©union */
  CountryCode_Re = 180,

  /** Romania */
  CountryCode_Ro = 181,

  /** Russian Federation */
  CountryCode_Ru = 182,

  /** Rwanda */
  CountryCode_Rw = 183,

  /** Saint BarthÃ©lemy */
  CountryCode_Bl = 184,

  /** "Saint Helena, Ascension and Tristan da Cunha" */
  CountryCode_Sh = 185,

  /** Saint Kitts and Nevis */
  CountryCode_Kn = 186,

  /** Saint Lucia */
  CountryCode_Lc = 187,

  /** Saint Martin (French part) */
  CountryCode_Mf = 188,

  /** Saint Pierre and Miquelon */
  CountryCode_Pm = 189,

  /** Saint Vincent and the Grenadines */
  CountryCode_Vc = 190,

  /** Samoa */
  CountryCode_Ws = 191,

  /** San Marino */
  CountryCode_Sm = 192,

  /** Sao Tome and Principe */
  CountryCode_St = 193,

  /** Saudi Arabia */
  CountryCode_Sa = 194,

  /** Senegal */
  CountryCode_Sn = 195,

  /** Serbia */
  CountryCode_Rs = 196,

  /** Seychelles */
  CountryCode_Sc = 197,

  /** Sierra Leone */
  CountryCode_Sl = 198,

  /** Singapore */
  CountryCode_Sg = 199,

  /** Sint Maarten (Dutch part) */
  CountryCode_Sx = 200,

  /** Slovakia */
  CountryCode_Sk = 201,

  /** Slovenia */
  CountryCode_Si = 202,

  /** Solomon Islands */
  CountryCode_Sb = 203,

  /** Somalia */
  CountryCode_So = 204,

  /** South Africa */
  CountryCode_Za = 205,

  /** South Georgia and the South Sandwich Islands */
  CountryCode_Gs = 206,

  /** South Sudan */
  CountryCode_Ss = 207,

  /** Spain */
  CountryCode_Es = 208,

  /** Sri Lanka */
  CountryCode_Lk = 209,

  /** Sudan */
  CountryCode_Sd = 210,

  /** Suriname */
  CountryCode_Sr = 211,

  /** Svalbard and Jan Mayen */
  CountryCode_Sj = 212,

  /** Swaziland */
  CountryCode_Sz = 213,

  /** Sweden */
  CountryCode_Se = 214,

  /** Switzerland */
  CountryCode_Ch = 215,

  /** Syrian Arab Republic */
  CountryCode_Sy = 216,

  /** "Taiwan, Province of China" */
  CountryCode_Tw = 217,

  /** Tajikistan */
  CountryCode_Tj = 218,

  /** "Tanzania, United Republic of" */
  CountryCode_Tz = 219,

  /** Thailand */
  CountryCode_Th = 220,

  /** Timor-Leste */
  CountryCode_Tl = 221,

  /** Togo */
  CountryCode_Tg = 222,

  /** Tokelau */
  CountryCode_Tk = 223,

  /** Tonga */
  CountryCode_To = 224,

  /** Trinidad and Tobago */
  CountryCode_Tt = 225,

  /** Tunisia */
  CountryCode_Tn = 226,

  /** Turkey */
  CountryCode_Tr = 227,

  /** Turkmenistan */
  CountryCode_Tm = 228,

  /** Turks and Caicos Islands */
  CountryCode_Tc = 229,

  /** Tuvalu */
  CountryCode_Tv = 230,

  /** Uganda */
  CountryCode_Ug = 231,

  /** Ukraine */
  CountryCode_Ua = 232,

  /** United Arab Emirates */
  CountryCode_Ae = 233,

  /** United Kingdom */
  CountryCode_Gb = 234,

  /** United States */
  CountryCode_Us = 235,

  /** United States Minor Outlying Islands */
  CountryCode_Um = 236,

  /** Uruguay */
  CountryCode_Uy = 237,

  /** Uzbekistan */
  CountryCode_Uz = 238,

  /** Vanuatu */
  CountryCode_Vu = 239,

  /** "Venezuela, Bolivarian Republic of" */
  CountryCode_Ve = 240,

  /** Viet Nam */
  CountryCode_Vn = 241,

  /** "Virgin Islands, British" */
  CountryCode_Vg = 242,

  /** "Virgin Islands, U.S." */
  CountryCode_Vi = 243,

  /** Wallis and Futuna */
  CountryCode_Wf = 244,

  /** Western Sahara */
  CountryCode_Eh = 245,

  /** Yemen */
  CountryCode_Ye = 246,

  /** Zambia */
  CountryCode_Zm = 247,

  /** Zimbabwe */
  CountryCode_Zw = 248,
};

GPBEnumDescriptor *CountryCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CountryCode_IsValidValue(int32_t value);

#pragma mark - CountryCodeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface CountryCodeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
