<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common/Address.proto

namespace Workstream\Protocol\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Workstream.Protocol.Common.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address1 = 1;</code>
     */
    protected $address1 = '';
    /**
     * Generated from protobuf field <code>string address2 = 2;</code>
     */
    protected $address2 = '';
    /**
     * Generated from protobuf field <code>string city = 3;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string county = 4;</code>
     */
    protected $county = '';
    /**
     * Generated from protobuf field <code>string zip = 20;</code>
     */
    protected $zip = '';
    /**
     * Generated from protobuf field <code>string country_sub_division_code = 19;</code>
     */
    protected $country_sub_division_code = '';
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.CountryCode country_code = 21;</code>
     */
    protected $country_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address1
     *     @type string $address2
     *     @type string $city
     *     @type string $county
     *     @type string $zip
     *     @type string $country_sub_division_code
     *     @type int $country_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Address::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address1 = 1;</code>
     * @return string
     */
    public function getAddress1()
    {
        return $this->address1;
    }

    /**
     * Generated from protobuf field <code>string address1 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress1($var)
    {
        GPBUtil::checkString($var, True);
        $this->address1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address2 = 2;</code>
     * @return string
     */
    public function getAddress2()
    {
        return $this->address2;
    }

    /**
     * Generated from protobuf field <code>string address2 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress2($var)
    {
        GPBUtil::checkString($var, True);
        $this->address2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 3;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string county = 4;</code>
     * @return string
     */
    public function getCounty()
    {
        return $this->county;
    }

    /**
     * Generated from protobuf field <code>string county = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCounty($var)
    {
        GPBUtil::checkString($var, True);
        $this->county = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string zip = 20;</code>
     * @return string
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * Generated from protobuf field <code>string zip = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setZip($var)
    {
        GPBUtil::checkString($var, True);
        $this->zip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country_sub_division_code = 19;</code>
     * @return string
     */
    public function getCountrySubDivisionCode()
    {
        return $this->country_sub_division_code;
    }

    /**
     * Generated from protobuf field <code>string country_sub_division_code = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setCountrySubDivisionCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_sub_division_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.CountryCode country_code = 21;</code>
     * @return int
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.CountryCode country_code = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkEnum($var, \Workstream\Protocol\Common\CountryCode::class);
        $this->country_code = $var;

        return $this;
    }

}

