// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common/Phone.proto

package Workstream.Protocol.Common;

public final class PhoneOuterClass {
  private PhoneOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Workstream.Protocol.Common.Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string country_code = 1;</code>
     * @return The countryCode.
     */
    java.lang.String getCountryCode();
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string country_code = 1;</code>
     * @return The bytes for countryCode.
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string number = 2;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string extension = 3;</code>
     * @return The extension.
     */
    java.lang.String getExtension();
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string extension = 3;</code>
     * @return The bytes for extension.
     */
    com.google.protobuf.ByteString
        getExtensionBytes();
  }
  /**
   * Protobuf type {@code Workstream.Protocol.Common.Phone}
   */
  public static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Workstream.Protocol.Common.Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      countryCode_ = "";
      number_ = "";
      extension_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Phone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Phone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              countryCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              extension_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Workstream.Protocol.Common.PhoneOuterClass.internal_static_Workstream_Protocol_Common_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Workstream.Protocol.Common.PhoneOuterClass.internal_static_Workstream_Protocol_Common_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Workstream.Protocol.Common.PhoneOuterClass.Phone.class, Workstream.Protocol.Common.PhoneOuterClass.Phone.Builder.class);
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object countryCode_;
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string country_code = 1;</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string country_code = 1;</code>
     * @return The bytes for countryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object number_;
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string number = 2;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTENSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object extension_;
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string extension = 3;</code>
     * @return The extension.
     */
    @java.lang.Override
    public java.lang.String getExtension() {
      java.lang.Object ref = extension_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extension_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * need Vincent's review
     * </pre>
     *
     * <code>string extension = 3;</code>
     * @return The bytes for extension.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtensionBytes() {
      java.lang.Object ref = extension_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCountryCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, countryCode_);
      }
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, number_);
      }
      if (!getExtensionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, extension_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCountryCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, countryCode_);
      }
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, number_);
      }
      if (!getExtensionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, extension_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Workstream.Protocol.Common.PhoneOuterClass.Phone)) {
        return super.equals(obj);
      }
      Workstream.Protocol.Common.PhoneOuterClass.Phone other = (Workstream.Protocol.Common.PhoneOuterClass.Phone) obj;

      if (!getCountryCode()
          .equals(other.getCountryCode())) return false;
      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!getExtension()
          .equals(other.getExtension())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCode().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
      hash = (53 * hash) + getExtension().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Workstream.Protocol.Common.PhoneOuterClass.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Workstream.Protocol.Common.PhoneOuterClass.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Workstream.Protocol.Common.Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Workstream.Protocol.Common.Phone)
        Workstream.Protocol.Common.PhoneOuterClass.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Workstream.Protocol.Common.PhoneOuterClass.internal_static_Workstream_Protocol_Common_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Workstream.Protocol.Common.PhoneOuterClass.internal_static_Workstream_Protocol_Common_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Workstream.Protocol.Common.PhoneOuterClass.Phone.class, Workstream.Protocol.Common.PhoneOuterClass.Phone.Builder.class);
      }

      // Construct using Workstream.Protocol.Common.PhoneOuterClass.Phone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        countryCode_ = "";

        number_ = "";

        extension_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Workstream.Protocol.Common.PhoneOuterClass.internal_static_Workstream_Protocol_Common_Phone_descriptor;
      }

      @java.lang.Override
      public Workstream.Protocol.Common.PhoneOuterClass.Phone getDefaultInstanceForType() {
        return Workstream.Protocol.Common.PhoneOuterClass.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public Workstream.Protocol.Common.PhoneOuterClass.Phone build() {
        Workstream.Protocol.Common.PhoneOuterClass.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Workstream.Protocol.Common.PhoneOuterClass.Phone buildPartial() {
        Workstream.Protocol.Common.PhoneOuterClass.Phone result = new Workstream.Protocol.Common.PhoneOuterClass.Phone(this);
        result.countryCode_ = countryCode_;
        result.number_ = number_;
        result.extension_ = extension_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Workstream.Protocol.Common.PhoneOuterClass.Phone) {
          return mergeFrom((Workstream.Protocol.Common.PhoneOuterClass.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Workstream.Protocol.Common.PhoneOuterClass.Phone other) {
        if (other == Workstream.Protocol.Common.PhoneOuterClass.Phone.getDefaultInstance()) return this;
        if (!other.getCountryCode().isEmpty()) {
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (!other.getExtension().isEmpty()) {
          extension_ = other.extension_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Workstream.Protocol.Common.PhoneOuterClass.Phone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Workstream.Protocol.Common.PhoneOuterClass.Phone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string country_code = 1;</code>
       * @return The countryCode.
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string country_code = 1;</code>
       * @return The bytes for countryCode.
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string country_code = 1;</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string country_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string country_code = 1;</code>
       * @param value The bytes for countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string number = 2;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string number = 2;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string number = 2;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string number = 2;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extension_ = "";
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string extension = 3;</code>
       * @return The extension.
       */
      public java.lang.String getExtension() {
        java.lang.Object ref = extension_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extension_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string extension = 3;</code>
       * @return The bytes for extension.
       */
      public com.google.protobuf.ByteString
          getExtensionBytes() {
        java.lang.Object ref = extension_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extension_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string extension = 3;</code>
       * @param value The extension to set.
       * @return This builder for chaining.
       */
      public Builder setExtension(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extension_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string extension = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtension() {
        
        extension_ = getDefaultInstance().getExtension();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * need Vincent's review
       * </pre>
       *
       * <code>string extension = 3;</code>
       * @param value The bytes for extension to set.
       * @return This builder for chaining.
       */
      public Builder setExtensionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extension_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Workstream.Protocol.Common.Phone)
    }

    // @@protoc_insertion_point(class_scope:Workstream.Protocol.Common.Phone)
    private static final Workstream.Protocol.Common.PhoneOuterClass.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Workstream.Protocol.Common.PhoneOuterClass.Phone();
    }

    public static Workstream.Protocol.Common.PhoneOuterClass.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Phone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Workstream.Protocol.Common.PhoneOuterClass.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Workstream_Protocol_Common_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Workstream_Protocol_Common_Phone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Common/Phone.proto\022\032Workstream.Protoco" +
      "l.Common\"@\n\005Phone\022\024\n\014country_code\030\001 \001(\t\022" +
      "\016\n\006number\030\002 \001(\t\022\021\n\textension\030\003 \001(\tB\"Z wo" +
      "rkstream_protocol/common/phoneb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Workstream_Protocol_Common_Phone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Workstream_Protocol_Common_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Workstream_Protocol_Common_Phone_descriptor,
        new java.lang.String[] { "CountryCode", "Number", "Extension", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
