<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Onboarding.proto

namespace Workstream\Protocol\Onboarding;

if (false) {
    /**
     * This class is deprecated. Use Workstream\Protocol\Onboarding\CompanyStaffEvent\CompanyStaffStatus instead.
     * @deprecated
     */
    class CompanyStaffEvent_CompanyStaffStatus {}
}
class_exists(CompanyStaffEvent\CompanyStaffStatus::class);
@trigger_error('Workstream\Protocol\Onboarding\CompanyStaffEvent_CompanyStaffStatus is deprecated and will be removed in the next major release. Use Workstream\Protocol\Onboarding\CompanyStaffEvent\CompanyStaffStatus instead', E_USER_DEPRECATED);

