<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Onboarding.proto

namespace Workstream\Protocol\Onboarding;

if (false) {
    /**
     * This class is deprecated. Use Workstream\Protocol\Onboarding\CompanyEvent\CompanyStatus instead.
     * @deprecated
     */
    class CompanyEvent_CompanyStatus {}
}
class_exists(CompanyEvent\CompanyStatus::class);
@trigger_error('Workstream\Protocol\Onboarding\CompanyEvent_CompanyStatus is deprecated and will be removed in the next major release. Use Workstream\Protocol\Onboarding\CompanyEvent\CompanyStatus instead', E_USER_DEPRECATED);

