<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Onboarding.proto

namespace Workstream\Protocol\Onboarding;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Workstream.Protocol.Onboarding.EmergencyContact</code>
 */
class EmergencyContact extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string relationship = 1;</code>
     */
    protected $relationship = '';
    /**
     * Generated from protobuf field <code>string first_name = 2;</code>
     */
    protected $first_name = '';
    /**
     * Generated from protobuf field <code>string last_name = 3;</code>
     */
    protected $last_name = '';
    /**
     * Generated from protobuf field <code>string home_phone = 4;</code>
     */
    protected $home_phone = '';
    /**
     * Generated from protobuf field <code>string work_phone = 5;</code>
     */
    protected $work_phone = '';
    /**
     * Generated from protobuf field <code>string email = 6;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address address = 7;</code>
     */
    protected $address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $relationship
     *     @type string $first_name
     *     @type string $last_name
     *     @type string $home_phone
     *     @type string $work_phone
     *     @type string $email
     *     @type \Workstream\Protocol\Common\Address $address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string relationship = 1;</code>
     * @return string
     */
    public function getRelationship()
    {
        return $this->relationship;
    }

    /**
     * Generated from protobuf field <code>string relationship = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRelationship($var)
    {
        GPBUtil::checkString($var, True);
        $this->relationship = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string first_name = 2;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Generated from protobuf field <code>string first_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 3;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string home_phone = 4;</code>
     * @return string
     */
    public function getHomePhone()
    {
        return $this->home_phone;
    }

    /**
     * Generated from protobuf field <code>string home_phone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setHomePhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->home_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string work_phone = 5;</code>
     * @return string
     */
    public function getWorkPhone()
    {
        return $this->work_phone;
    }

    /**
     * Generated from protobuf field <code>string work_phone = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->work_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address address = 7;</code>
     * @return \Workstream\Protocol\Common\Address
     */
    public function getAddress()
    {
        return isset($this->address) ? $this->address : null;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address address = 7;</code>
     * @param \Workstream\Protocol\Common\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Workstream\Protocol\Common\Address::class);
        $this->address = $var;

        return $this;
    }

}

