<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Onboarding.proto

namespace Workstream\Protocol\Onboarding;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Workstream.Protocol.Onboarding.EmployeeInformationEvent</code>
 */
class EmployeeInformationEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 4;</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>int64 company_id = 5;</code>
     */
    protected $company_id = 0;
    /**
     * Generated from protobuf field <code>int64 employee_id = 6;</code>
     */
    protected $employee_id = 0;
    /**
     * Generated from protobuf field <code>string first_name = 7;</code>
     */
    protected $first_name = '';
    /**
     * Generated from protobuf field <code>string middle_name = 8;</code>
     */
    protected $middle_name = '';
    /**
     * Generated from protobuf field <code>string last_name = 9;</code>
     */
    protected $last_name = '';
    /**
     * Generated from protobuf field <code>string prior_last_name = 10;</code>
     */
    protected $prior_last_name = '';
    /**
     * Generated from protobuf field <code>string prefered_name = 11;</code>
     */
    protected $prefered_name = '';
    /**
     * Generated from protobuf field <code>string salutation = 12;</code>
     */
    protected $salutation = '';
    /**
     * Generated from protobuf field <code>string ethnicity = 13;</code>
     */
    protected $ethnicity = '';
    /**
     * Generated from protobuf field <code>string gender = 14;</code>
     */
    protected $gender = '';
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Onboarding.MaritalStatus marital_status = 15;</code>
     */
    protected $marital_status = 0;
    /**
     * Generated from protobuf field <code>string ssn = 16;</code>
     */
    protected $ssn = '';
    /**
     * Generated from protobuf field <code>bool smoker = 17;</code>
     */
    protected $smoker = false;
    /**
     * Generated from protobuf field <code>string nationality = 18;</code>
     */
    protected $nationality = '';
    /**
     * Generated from protobuf field <code>string date_of_birth = 19;</code>
     */
    protected $date_of_birth = '';
    /**
     * Home Address
     *
     * Generated from protobuf field <code>string home_email = 31;</code>
     */
    protected $home_email = '';
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Phone home_phone = 32;</code>
     */
    protected $home_phone = null;
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address home_address = 33;</code>
     */
    protected $home_address = null;
    /**
     * Work Address
     *
     * Generated from protobuf field <code>string work_location_name = 41;</code>
     */
    protected $work_location_name = '';
    /**
     * Generated from protobuf field <code>string work_email = 42;</code>
     */
    protected $work_email = '';
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Phone work_phone = 43;</code>
     */
    protected $work_phone = null;
    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address work_address = 44;</code>
     */
    protected $work_address = null;
    /**
     * Emergency Contact
     *
     * Generated from protobuf field <code>repeated .Workstream.Protocol.Onboarding.EmergencyContact emergency_contact = 51;</code>
     */
    private $emergency_contact;
    /**
     * Employment details
     *
     * Generated from protobuf field <code>string apply_date = 52;</code>
     */
    protected $apply_date = '';
    /**
     * Generated from protobuf field <code>string hire_date = 53;</code>
     */
    protected $hire_date = '';
    /**
     * Generated from protobuf field <code>string start_date = 54;</code>
     */
    protected $start_date = '';
    /**
     * Generated from protobuf field <code>string termination_date = 55;</code>
     */
    protected $termination_date = '';
    /**
     * Generated from protobuf field <code>string job_title = 56;</code>
     */
    protected $job_title = '';
    /**
     * Generated from protobuf field <code>string department_name = 57;</code>
     */
    protected $department_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type int|string $id
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type int|string $company_id
     *     @type int|string $employee_id
     *     @type string $first_name
     *     @type string $middle_name
     *     @type string $last_name
     *     @type string $prior_last_name
     *     @type string $prefered_name
     *     @type string $salutation
     *     @type string $ethnicity
     *     @type string $gender
     *     @type int $marital_status
     *     @type string $ssn
     *     @type bool $smoker
     *     @type string $nationality
     *     @type string $date_of_birth
     *     @type string $home_email
     *           Home Address
     *     @type \Workstream\Protocol\Common\Phone $home_phone
     *     @type \Workstream\Protocol\Common\Address $home_address
     *     @type string $work_location_name
     *           Work Address
     *     @type string $work_email
     *     @type \Workstream\Protocol\Common\Phone $work_phone
     *     @type \Workstream\Protocol\Common\Address $work_address
     *     @type \Workstream\Protocol\Onboarding\EmergencyContact[]|\Google\Protobuf\Internal\RepeatedField $emergency_contact
     *           Emergency Contact
     *     @type string $apply_date
     *           Employment details
     *     @type string $hire_date
     *     @type string $start_date
     *     @type string $termination_date
     *     @type string $job_title
     *     @type string $department_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return isset($this->created_at) ? $this->created_at : null;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdatedAt()
    {
        return isset($this->updated_at) ? $this->updated_at : null;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 5;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 employee_id = 6;</code>
     * @return int|string
     */
    public function getEmployeeId()
    {
        return $this->employee_id;
    }

    /**
     * Generated from protobuf field <code>int64 employee_id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEmployeeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->employee_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string first_name = 7;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Generated from protobuf field <code>string first_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string middle_name = 8;</code>
     * @return string
     */
    public function getMiddleName()
    {
        return $this->middle_name;
    }

    /**
     * Generated from protobuf field <code>string middle_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMiddleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->middle_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 9;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prior_last_name = 10;</code>
     * @return string
     */
    public function getPriorLastName()
    {
        return $this->prior_last_name;
    }

    /**
     * Generated from protobuf field <code>string prior_last_name = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPriorLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->prior_last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prefered_name = 11;</code>
     * @return string
     */
    public function getPreferedName()
    {
        return $this->prefered_name;
    }

    /**
     * Generated from protobuf field <code>string prefered_name = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPreferedName($var)
    {
        GPBUtil::checkString($var, True);
        $this->prefered_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string salutation = 12;</code>
     * @return string
     */
    public function getSalutation()
    {
        return $this->salutation;
    }

    /**
     * Generated from protobuf field <code>string salutation = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setSalutation($var)
    {
        GPBUtil::checkString($var, True);
        $this->salutation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ethnicity = 13;</code>
     * @return string
     */
    public function getEthnicity()
    {
        return $this->ethnicity;
    }

    /**
     * Generated from protobuf field <code>string ethnicity = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setEthnicity($var)
    {
        GPBUtil::checkString($var, True);
        $this->ethnicity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gender = 14;</code>
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>string gender = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->gender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Onboarding.MaritalStatus marital_status = 15;</code>
     * @return int
     */
    public function getMaritalStatus()
    {
        return $this->marital_status;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Onboarding.MaritalStatus marital_status = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setMaritalStatus($var)
    {
        GPBUtil::checkEnum($var, \Workstream\Protocol\Onboarding\MaritalStatus::class);
        $this->marital_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ssn = 16;</code>
     * @return string
     */
    public function getSsn()
    {
        return $this->ssn;
    }

    /**
     * Generated from protobuf field <code>string ssn = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setSsn($var)
    {
        GPBUtil::checkString($var, True);
        $this->ssn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool smoker = 17;</code>
     * @return bool
     */
    public function getSmoker()
    {
        return $this->smoker;
    }

    /**
     * Generated from protobuf field <code>bool smoker = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setSmoker($var)
    {
        GPBUtil::checkBool($var);
        $this->smoker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nationality = 18;</code>
     * @return string
     */
    public function getNationality()
    {
        return $this->nationality;
    }

    /**
     * Generated from protobuf field <code>string nationality = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setNationality($var)
    {
        GPBUtil::checkString($var, True);
        $this->nationality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date_of_birth = 19;</code>
     * @return string
     */
    public function getDateOfBirth()
    {
        return $this->date_of_birth;
    }

    /**
     * Generated from protobuf field <code>string date_of_birth = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setDateOfBirth($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_of_birth = $var;

        return $this;
    }

    /**
     * Home Address
     *
     * Generated from protobuf field <code>string home_email = 31;</code>
     * @return string
     */
    public function getHomeEmail()
    {
        return $this->home_email;
    }

    /**
     * Home Address
     *
     * Generated from protobuf field <code>string home_email = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setHomeEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->home_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Phone home_phone = 32;</code>
     * @return \Workstream\Protocol\Common\Phone
     */
    public function getHomePhone()
    {
        return isset($this->home_phone) ? $this->home_phone : null;
    }

    public function hasHomePhone()
    {
        return isset($this->home_phone);
    }

    public function clearHomePhone()
    {
        unset($this->home_phone);
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Phone home_phone = 32;</code>
     * @param \Workstream\Protocol\Common\Phone $var
     * @return $this
     */
    public function setHomePhone($var)
    {
        GPBUtil::checkMessage($var, \Workstream\Protocol\Common\Phone::class);
        $this->home_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address home_address = 33;</code>
     * @return \Workstream\Protocol\Common\Address
     */
    public function getHomeAddress()
    {
        return isset($this->home_address) ? $this->home_address : null;
    }

    public function hasHomeAddress()
    {
        return isset($this->home_address);
    }

    public function clearHomeAddress()
    {
        unset($this->home_address);
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address home_address = 33;</code>
     * @param \Workstream\Protocol\Common\Address $var
     * @return $this
     */
    public function setHomeAddress($var)
    {
        GPBUtil::checkMessage($var, \Workstream\Protocol\Common\Address::class);
        $this->home_address = $var;

        return $this;
    }

    /**
     * Work Address
     *
     * Generated from protobuf field <code>string work_location_name = 41;</code>
     * @return string
     */
    public function getWorkLocationName()
    {
        return $this->work_location_name;
    }

    /**
     * Work Address
     *
     * Generated from protobuf field <code>string work_location_name = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkLocationName($var)
    {
        GPBUtil::checkString($var, True);
        $this->work_location_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string work_email = 42;</code>
     * @return string
     */
    public function getWorkEmail()
    {
        return $this->work_email;
    }

    /**
     * Generated from protobuf field <code>string work_email = 42;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->work_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Phone work_phone = 43;</code>
     * @return \Workstream\Protocol\Common\Phone
     */
    public function getWorkPhone()
    {
        return isset($this->work_phone) ? $this->work_phone : null;
    }

    public function hasWorkPhone()
    {
        return isset($this->work_phone);
    }

    public function clearWorkPhone()
    {
        unset($this->work_phone);
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Phone work_phone = 43;</code>
     * @param \Workstream\Protocol\Common\Phone $var
     * @return $this
     */
    public function setWorkPhone($var)
    {
        GPBUtil::checkMessage($var, \Workstream\Protocol\Common\Phone::class);
        $this->work_phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address work_address = 44;</code>
     * @return \Workstream\Protocol\Common\Address
     */
    public function getWorkAddress()
    {
        return isset($this->work_address) ? $this->work_address : null;
    }

    public function hasWorkAddress()
    {
        return isset($this->work_address);
    }

    public function clearWorkAddress()
    {
        unset($this->work_address);
    }

    /**
     * Generated from protobuf field <code>.Workstream.Protocol.Common.Address work_address = 44;</code>
     * @param \Workstream\Protocol\Common\Address $var
     * @return $this
     */
    public function setWorkAddress($var)
    {
        GPBUtil::checkMessage($var, \Workstream\Protocol\Common\Address::class);
        $this->work_address = $var;

        return $this;
    }

    /**
     * Emergency Contact
     *
     * Generated from protobuf field <code>repeated .Workstream.Protocol.Onboarding.EmergencyContact emergency_contact = 51;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmergencyContact()
    {
        return $this->emergency_contact;
    }

    /**
     * Emergency Contact
     *
     * Generated from protobuf field <code>repeated .Workstream.Protocol.Onboarding.EmergencyContact emergency_contact = 51;</code>
     * @param \Workstream\Protocol\Onboarding\EmergencyContact[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmergencyContact($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Workstream\Protocol\Onboarding\EmergencyContact::class);
        $this->emergency_contact = $arr;

        return $this;
    }

    /**
     * Employment details
     *
     * Generated from protobuf field <code>string apply_date = 52;</code>
     * @return string
     */
    public function getApplyDate()
    {
        return $this->apply_date;
    }

    /**
     * Employment details
     *
     * Generated from protobuf field <code>string apply_date = 52;</code>
     * @param string $var
     * @return $this
     */
    public function setApplyDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->apply_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hire_date = 53;</code>
     * @return string
     */
    public function getHireDate()
    {
        return $this->hire_date;
    }

    /**
     * Generated from protobuf field <code>string hire_date = 53;</code>
     * @param string $var
     * @return $this
     */
    public function setHireDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->hire_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string start_date = 54;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>string start_date = 54;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string termination_date = 55;</code>
     * @return string
     */
    public function getTerminationDate()
    {
        return $this->termination_date;
    }

    /**
     * Generated from protobuf field <code>string termination_date = 55;</code>
     * @param string $var
     * @return $this
     */
    public function setTerminationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->termination_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string job_title = 56;</code>
     * @return string
     */
    public function getJobTitle()
    {
        return $this->job_title;
    }

    /**
     * Generated from protobuf field <code>string job_title = 56;</code>
     * @param string $var
     * @return $this
     */
    public function setJobTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string department_name = 57;</code>
     * @return string
     */
    public function getDepartmentName()
    {
        return $this->department_name;
    }

    /**
     * Generated from protobuf field <code>string department_name = 57;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartmentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->department_name = $var;

        return $this;
    }

}

