<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Onboarding.proto

namespace Workstream\Protocol\Onboarding;

use UnexpectedValueException;

/**
 * Protobuf type <code>Workstream.Protocol.Onboarding.MaritalStatus</code>
 */
class MaritalStatus
{
    /**
     * Generated from protobuf enum <code>MARRIED = 0;</code>
     */
    const MARRIED = 0;
    /**
     * Generated from protobuf enum <code>DIVORCED = 1;</code>
     */
    const DIVORCED = 1;
    /**
     * Generated from protobuf enum <code>WIDOWED = 2;</code>
     */
    const WIDOWED = 2;
    /**
     * Generated from protobuf enum <code>NEVER_MARRIED = 3;</code>
     */
    const NEVER_MARRIED = 3;
    /**
     * Generated from protobuf enum <code>SEPARATED = 4;</code>
     */
    const SEPARATED = 4;

    private static $valueToName = [
        self::MARRIED => 'MARRIED',
        self::DIVORCED => 'DIVORCED',
        self::WIDOWED => 'WIDOWED',
        self::NEVER_MARRIED => 'NEVER_MARRIED',
        self::SEPARATED => 'SEPARATED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

