# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Onboarding.proto

require 'google/protobuf'

require 'Common/Phone_pb'
require 'Common/Address_pb'
require 'google/protobuf/timestamp_pb'
require 'Common/Date_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Onboarding.proto", :syntax => :proto3) do
    add_message "Workstream.Protocol.Onboarding.CompanyEvent" do
      optional :uuid, :string, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :deleted_at, :message, 4, "google.protobuf.Timestamp"
      optional :name, :string, 5
      optional :status, :string, 6
    end
    add_message "Workstream.Protocol.Onboarding.EmployeeEvent" do
      optional :uuid, :string, 1
      optional :company_uuid, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
      optional :deleted_at, :message, 5, "google.protobuf.Timestamp"
    end
    add_message "Workstream.Protocol.Onboarding.CompanyStaffEvent" do
      optional :uuid, :string, 1
      optional :company_uuid, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
      optional :deleted_at, :message, 5, "google.protobuf.Timestamp"
      optional :status, :string, 6
      optional :name, :string, 7
      optional :email, :string, 8
      optional :phone, :message, 9, "Workstream.Protocol.Common.Phone"
    end
    add_message "Workstream.Protocol.Onboarding.EmergencyContact" do
      optional :relationship, :string, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
      optional :home_phone, :string, 4
      optional :work_phone, :string, 5
      optional :email, :string, 6
      optional :address, :message, 7, "Workstream.Protocol.Common.Address"
    end
    add_message "Workstream.Protocol.Onboarding.EmployeeInformationEvent" do
      optional :uuid, :string, 1
      optional :employee_uuid, :string, 2
      optional :company_uuid, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      optional :deleted_at, :message, 6, "google.protobuf.Timestamp"
      optional :first_name, :string, 7
      optional :middle_name, :string, 8
      optional :last_name, :string, 9
      optional :prior_last_name, :string, 10
      optional :preferred_name, :string, 11
      optional :salutation, :string, 12
      optional :ethnicity, :string, 13
      optional :gender, :string, 14
      optional :marital_status, :string, 15
      optional :ssn, :string, 16
      optional :smoker, :bool, 17
      optional :nationality, :string, 18
      optional :date_of_birth, :message, 19, "Workstream.Protocol.Common.Date"
      optional :middle_initial, :string, 20
      optional :home_email, :string, 31
      optional :home_phone, :message, 32, "Workstream.Protocol.Common.Phone"
      optional :home_address, :message, 33, "Workstream.Protocol.Common.Address"
      optional :work_location_name, :string, 41
      optional :work_email, :string, 42
      optional :work_phone, :message, 43, "Workstream.Protocol.Common.Phone"
      optional :work_address, :message, 44, "Workstream.Protocol.Common.Address"
      repeated :emergency_contact, :message, 51, "Workstream.Protocol.Onboarding.EmergencyContact"
      optional :apply_date, :message, 52, "Workstream.Protocol.Common.Date"
      optional :hire_date, :message, 53, "Workstream.Protocol.Common.Date"
      optional :start_date, :message, 54, "Workstream.Protocol.Common.Date"
      optional :termination_date, :message, 55, "Workstream.Protocol.Common.Date"
      optional :job_title, :string, 56
      optional :department_name, :string, 57
    end
    add_message "Workstream.Protocol.Onboarding.EmployeeInitialStateEvent" do
      optional :uuid, :string, 1
      optional :id, :int64, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
      optional :deleted_at, :message, 5, "google.protobuf.Timestamp"
      optional :employee_uuid, :string, 6
      optional :first_name, :string, 7
      optional :last_name, :string, 8
    end
  end
end

module Workstream
  module Protocol
    module Onboarding
      CompanyEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Onboarding.CompanyEvent").msgclass
      EmployeeEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Onboarding.EmployeeEvent").msgclass
      CompanyStaffEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Onboarding.CompanyStaffEvent").msgclass
      EmergencyContact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Onboarding.EmergencyContact").msgclass
      EmployeeInformationEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Onboarding.EmployeeInformationEvent").msgclass
      EmployeeInitialStateEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Onboarding.EmployeeInitialStateEvent").msgclass
    end
  end
end
