# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common/Address.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Common/Address.proto", :syntax => :proto3) do
    add_message "Workstream.Protocol.Common.Address" do
      optional :line_one, :string, 1
      optional :line_two, :string, 2
      optional :city, :string, 3
      optional :county, :string, 4
      optional :postal_code, :string, 5
      optional :country_subdivision, :string, 6
      optional :country, :string, 7
    end
  end
end

module Workstream
  module Protocol
    module Common
      Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Common.Address").msgclass
    end
  end
end
