# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common/Date.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Common/Date.proto", :syntax => :proto3) do
    add_message "Workstream.Protocol.Common.Date" do
      optional :year, :int32, 1
      optional :month, :int32, 2
      optional :day, :int32, 3
    end
  end
end

module Workstream
  module Protocol
    module Common
      Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Common.Date").msgclass
    end
  end
end
