# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common/Phone.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Common/Phone.proto", :syntax => :proto3) do
    add_message "Workstream.Protocol.Common.Phone" do
      optional :country_code, :string, 1
      optional :number, :string, 2
      optional :extension, :string, 3
    end
  end
end

module Workstream
  module Protocol
    module Common
      Phone = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Workstream.Protocol.Common.Phone").msgclass
    end
  end
end
